services:
  facefusion:
    image: ghcr.io/hitechcloud-vietnam/facefusion-spark:latest
    container_name: nvidia-ai-hub-facefusion
    ports:
      - "7860:7860"
    volumes:
      - facefusion-models:/app/facefusion/.assets/models
      - facefusion-output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  facefusion-models:
  facefusion-output:
