services:
  flowise:
    image: ${FLOWISE_IMAGE}
    container_name: nvidia-ai-hub-flowise-rag
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-3089}:${PORT:-3000}"
    volumes:
      - ./data/flowise:/root/.flowise
    environment:
      PORT: ${PORT}
      FLOWISE_FILE_SIZE_LIMIT: ${FLOWISE_FILE_SIZE_LIMIT}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_PATH: ${DATABASE_PATH}
      LOG_PATH: ${LOG_PATH}
      SECRETKEY_PATH: ${SECRETKEY_PATH}
      BLOB_STORAGE_PATH: ${BLOB_STORAGE_PATH}
      FLOWISE_SECRETKEY_OVERWRITE: ${FLOWISE_SECRETKEY_OVERWRITE}
      TOKEN_HASH_SECRET: ${TOKEN_HASH_SECRET}
      EXPRESS_SESSION_SECRET: ${EXPRESS_SESSION_SECRET}
      JWT_AUTH_TOKEN_SECRET: ${JWT_AUTH_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      DISABLE_FLOWISE_TELEMETRY: ${DISABLE_FLOWISE_TELEMETRY}
      SHOW_COMMUNITY_NODES: ${SHOW_COMMUNITY_NODES}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      MODEL_LIST_CONFIG_JSON: ${MODEL_LIST_CONFIG_JSON}
      CORS_ORIGINS: ${CORS_ORIGINS}
      IFRAME_ORIGINS: ${IFRAME_ORIGINS}
      TOOL_FUNCTION_BUILTIN_DEP: ${TOOL_FUNCTION_BUILTIN_DEP}
      TOOL_FUNCTION_EXTERNAL_DEP: ${TOOL_FUNCTION_EXTERNAL_DEP}
      ALLOW_BUILTIN_DEP: ${ALLOW_BUILTIN_DEP}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped